#!/usr/bin/env python

import hashlib

def md5sum(filename,BLOCK_SIZE,BLOCK_LIMIT,BLOCK_OFFSET):
  blocks=[]
  cnt=0
  with open(filename, mode='rb') as f:
    d = hashlib.md5()
    while True:
      buf = f.read(BLOCK_SIZE) # 128 is smaller than the typical filesystem block
      if not buf:
        break
      #print
      #print cnt
      #print buf

      if BLOCK_OFFSET>0:
        BLOCK_OFFSET-=1
        continue
      
      dd = hashlib.md5()
      dd.update(buf)
      blocks.append(dd.hexdigest())
      d.update(buf)
      cnt+=1
      if BLOCK_LIMIT and cnt>=BLOCK_LIMIT:
        break
    return (d.hexdigest(),blocks)

import sys
import argparse

def main():
  parser = argparse.ArgumentParser()

  parser.add_argument('--block-size', '-b', action='store', dest="BLOCK_SIZE", type=int, default=16384, help='block size')
  parser.add_argument('--block-limit', '-n', action='store', dest="BLOCK_LIMIT", type=int, default=0, help='block limit')
  parser.add_argument('--block-offset', '-s', action='store', dest="BLOCK_OFFSET", type=int, default=0, help='block limit')
  parser.add_argument('--check', action='store_true', dest="check", default=False, help='check if block 0 repeats somewhere else')
  #parser.add_argument('--check-shift', action='store', dest="check_shift", type=int, default=0, help='check if shifted blocks are found (the argument specifies the length of shifted sequence)')
  parser.add_argument('file1', help='file1')
  parser.add_argument('file2', nargs='?', default="", help='file2')

  args = parser.parse_args()

  m1,blocks1 = md5sum(args.file1,args.BLOCK_SIZE,args.BLOCK_LIMIT,args.BLOCK_OFFSET)
  if args.file2:
    m2,blocks2 = md5sum(args.file2,args.BLOCK_SIZE,args.BLOCK_LIMIT,args.BLOCK_OFFSET)
    

  if args.check:
    print args.file1
    b0s = [i for i,b in enumerate(blocks1) if b == blocks1[0]]
    if len(b0s) > 1:
      print args.file1,': ERROR block 0 found repeated at the positions:',b0s
      sys.exit(2)
    sys.exit(0)


#   if args.check_shift:
#     print args.file1
#     streak=0
#     for i in range(len(blocks1)-1):
#       if blocks1[i] == blocks1[i+1]:
#         streak+=1
#       else:
#         streak=0
# 
#       print streak, blocks1[i], blocks1[i+1]
#         
#       if streak>args.check_shift:
#         print args.file1,': ERROR %s shifted blocks found at byte offset:',args.BLOCK_OFFSET+i*args.BLOCK_SIZE
#         sys.exit(2)
# 
#     sys.exit(0)
#       

  print "File block analyzer"
  for a in sorted(vars(args).keys()):
    print a,vars(args)[a]

  print

  diff1 = []
  diff2 = []

  def print_header():

    print "    offset   i file1",
    if args.file2:
      print "                            file2                            mod j"
    else:
      print

  print_header()
  for i in range(len(blocks1)):
     b1 = blocks1[i]
     if args.file2:
       b2 = blocks2[i]
     else:
       b2 = ''

     print "%10d %3d %s %s"%(args.BLOCK_SIZE*(i+args.BLOCK_OFFSET),args.BLOCK_OFFSET+i,b1,b2),
     if b1 != b2:
       print '***',
       diff1 = b1
       diff2 = b2
       repeats=[]
       rcnt=0
       for j,bb in enumerate(blocks1):
         if bb == b2:
           if rcnt<5: # limit the number of repeats to 5
             repeats.append(str(j))
           if rcnt==5:
             repeats.append('...')
           rcnt+=1
       print " ".join([str(int(v)+args.BLOCK_OFFSET) for v in repeats])
     else:
       print

  mod=""

  if args.file2:
    if m1!=m2:
      mod="***"
      assert(diff1 or diff2)
  else:
    m2=''

  print_header()

  print
  print "   total   --- %s %s %s"%(m1,m2,mod)


main()
