#!/usr/bin/env python

import os,sys
import subprocess

thisdir = os.path.abspath(os.path.normpath(os.path.dirname(sys.argv[0])))
smashdir=os.path.join(thisdir,'..')

dirs = {'thisdir':thisdir,'smashdir':smashdir}

os.environ['OWNCLOUD_MAX_PARALLEL'] = '10'

try:
 N = int(sys.argv[1])
except Exception,x:
 print """ERROR: missing or invalid argument (%s)

syntax: %s N
  
N is number of test repetitions, you may specify -1 for indefinite loop
"""% (repr(x),sys.argv[0])

 sys.exit(-1)
i = 1
dirs['options']="-o storm_filesize=1000"

cmd = '%(smashdir)s/bin/smash -c %(thisdir)s/smashbox.conf %(options)s %(smashdir)s/lib/test_storm.py' % dirs

#print cmd

while N:

 #print "test number",i
 
 rc = subprocess.call(cmd,shell=True)
 
 if rc != 0:
   break

 i+=1
 N-=1

