#!/usr/bin/env sh

echo "generating smashbox.conf" $PWD

cp -i smashbox.conf.template smashbox.conf

sed -i 's/smashdir.*/smashdir = "\/home\/piotr\/PROJECTS\/DeIC\/tests"/' smashbox.conf
sed -i 's/oc_account_name.*/oc_account_name = ""/' smashbox.conf
sed -i 's/oc_account_password.*/oc_account_password = ""/' smashbox.conf
sed -i 's/oc_server .*/oc_server = ""/' smashbox.conf
sed -i 's/oc_server_folder.*/oc_server_folder = "testfolder"/' smashbox.conf
sed -i 's/oc_ssl_enabled.*/oc_ssl_enabled = False/' smashbox.conf
#sed -i 's/oc_server_shell_cmd.*/oc_server_shell_cmd = ""/' smashbox.conf
#sed -i 's/oc_server_tools_path.*/oc_server_tools_path = ""/' smashbox.conf
sed -i 's/oc_sync_cmd.*/oc_sync_cmd = "\/usr\/bin\/owncloudcmd --trust"/' smashbox.conf

